version: '3'
services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8080:8080"  
    volumes:
      - ./app:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: cryptchat
      MYSQL_USER: root
      MYSQL_PASSWORD: 
